# These are supported funding model platforms

# GitHub Sponsors (preferred)
# github: [phoenix-tui]

# Open Collective
# open_collective: phoenix-tui

# Ko-fi
# ko_fi: phoenixtui

# Patreon
# patreon: phoenixtui

# Community Bridge
# community_bridge: phoenix-tui

# Liberapay
# liberapay: phoenix-tui

# IssueHunt
# issuehunt: phoenix-tui

# Custom URL
# custom: ['https://phoenix-tui.org/sponsor', 'https://buymeacoffee.com/phoenixtui']

# Note: Phoenix TUI Framework is currently in beta and does not have sponsorship set up yet.
# We'll enable sponsorship after v0.1.0 public release.
# For now, the best way to support us is:
# - Star the repo ⭐
# - Report bugs 🐛
# - Submit PRs 🔧
# - Spread the word 📢
